# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*   # Old Syntax
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0   # Old Syntax
windowrule = match:class ^$, match:title ^$, float on, no_focus on, pin off, fullscreen off 

# Float and pin PiP window
# windowrulev2 = move exact %w - %ww - 4 %h - %wh - 4,title:^(Pict1ure in picture)$
# windowrulev2 = size 20% 20%, title:^(Picture in picture)$

windowrule = match:title ^(Picture in picture)$, float on, pin on, keep_aspect_ratio on, focus_on_activate off, no_blur on, size (22%) window_h, move ((monitor_w*1)-window_w-8) ((monitor_h*1)-window_h-8), opacity 1.2
windowrule = match:class .scrcpy-wrapped, float on, keep_aspect_ratio on

windowrule = match:class spotify, workspace special:music,


# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
workspace = s[true], gapsout:16, border:true, bordersize:3