[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
show_hidden = true
show_symlink = true
show_preview = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "Yazi = {cwd}"

[preview]
wrap = "no"
tab_size = 2
image_delay = 20
image_filter = "triangle"
image_quality = 80

[opener]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix"}
]

[input]
cursor_blink = true
